# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpsnoop < Formula
  desc "Wireshark for MCP: a transparent proxy and TUI for debugging MCP traffic"
  homepage "https://github.com/kerlenton/mcpsnoop"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kerlenton/mcpsnoop/releases/download/v0.8.0/mcpsnoop_0.8.0_darwin_amd64.tar.gz"
      sha256 "647f1e594a585332080dce52094dae0643edfcb68558deb26d5a21ce7b04a1c1"

      define_method(:install) do
        bin.install "mcpsnoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kerlenton/mcpsnoop/releases/download/v0.8.0/mcpsnoop_0.8.0_darwin_arm64.tar.gz"
      sha256 "4a7acf7429a58af7ac256cf7f2ef4d2a3c6a5ba31a0f3fe978e235cc582079a2"

      define_method(:install) do
        bin.install "mcpsnoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerlenton/mcpsnoop/releases/download/v0.8.0/mcpsnoop_0.8.0_linux_amd64.tar.gz"
      sha256 "96f9e480efea97ed8d347f334515b129199244f5f7edae7022066e0e532f70c4"
      define_method(:install) do
        bin.install "mcpsnoop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerlenton/mcpsnoop/releases/download/v0.8.0/mcpsnoop_0.8.0_linux_arm64.tar.gz"
      sha256 "4501f33fd2eeaa8d7812d96aea598c8d7fd7a3d439831e35412fc845d91de3e4"
      define_method(:install) do
        bin.install "mcpsnoop"
      end
    end
  end

  test do
    system "#{bin}/mcpsnoop", "version"
  end
end
